# Generated by Django 2.2.24 on 2023-01-06 23:01

from django.db import migrations


def edit_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for apartment in Flat.objects.all():
        if apartment.construction_year >= 2015:
            apartment.new_building = True
        else:
            apartment.new_building = False
        apartment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(edit_new_building_field),
    ]
