# Generated by Django 3.2 on 2023-01-08 19:28

from django.db import migrations


def edit_owner_apartments(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.name)
        owner.apartments.set(flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230108_2113'),
    ]

    operations = [
        migrations.RunPython(edit_owner_apartments)
    ]
