# Generated by Django 3.2 on 2023-01-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='property.flat', verbose_name='Квартира на которую пожаловались'),
        ),
    ]
